Add dev guide
ROCm/jax pull request #188
Opened 2024-12-19 18:46 UTC by charleshofer

Add a guide for AMD developers that explains how to use new CI processes

Story: https://github.com/ROCm/frameworks-internal/issues/9948

2025-01-09 18:02 UTC, JehandadKhan approved these changes

2025-01-14 16:21 UTC, Ruturaj4 requested changes

2025-01-14 16:21 UTC, Ruturaj4 commented on rocm-downstream-dev-guide.md
> +4. Push your changes to a new feature branch in `rocm/jax` by running
What if there are already some commits on rocm-main which aren't yet upstreamed?

2025-01-14 16:21 UTC, Ruturaj4 commented on rocm-downstream-dev-guide.md
> +  c. If this is a change that we only want to keep in `rocm/jax` and not push into upstream,
Probably we should specify that a new branch gets created "ROCm:" prefix?

2025-01-14 16:21 UTC, Ruturaj4 commented on rocm-downstream-dev-guide.md
> +When using the `open-upstream` label to move changes to upstream, it's best to put the label on the PR when you either close or merge the PR. The GitHub Actions workflow that handles the `open-upstre
also, maybe if it is approved downstream and we got some comments from upstream, we can directly change the branch with "ROCm:" prefix?

2025-01-14 20:26 UTC, charleshofer commented on rocm-downstream-dev-guide.md
> +4. Push your changes to a new feature branch in `rocm/jax` by running
If it's already been merged and you deleted the original feature branch, you can just make a new branch from the downstream `main` branch, cherry-pick whatever commits you want to put upstream, and then open a PR against upstream `main`. I'll add a section for that.

I don't think we should be doing it that often. We only need to do that when commits we want upstream have been sitting in `rocm-main` for a while.

2025-01-14 20:31 UTC, charleshofer commented on rocm-downstream-dev-guide.md
> +  c. If this is a change that we only want to keep in `rocm/jax` and not push into upstream,
Done. I added that in the "a" sub-section.

2025-01-14 20:31 UTC, charleshofer commented on rocm-downstream-dev-guide.md
> +When using the `open-upstream` label to move changes to upstream, it's best to put the label on the PR when you either close or merge the PR. The GitHub Actions workflow that handles the `open-upstre
I put that in the "a" section as well.

2025-01-14 21:40 UTC, Ruturaj4 approved these changes
LGTM

2025-01-21 17:37 UTC, merged